### ISSUE TITLE
Add/remove not working in item variable in multi-lang environment 

### ISSUE THREAD

**Issue by taher-amici** [verbb/wishlist#101]
**Description**
craft.wishlist.item(elementId, listId = null, listType = null) not working in multi-lang environment 

**Steps to reproduce**
1. create toggle form and use it in secondary site.
2.

**Additional info**
- Plugin version: 1.4.12
- Craft version: 3.7.37
- Multi-site: Yes

```
<form method="POST" class="favorite-btn">
    <input type="hidden" name="action" value="wishlist/items/toggle">
    {{ csrfInput() }}
	{% set favUrl = craft.wishlist.item(property.id, null, 'favourites') %}

    <input type="hidden" name="elementId" value="{{ property.id }}">


    <button type="submit" value="Toggle in List">
	   {% if favUrl.getInList() %}
        <div class="absolute text-white outline-none top-6 right-6 remove-btn">
            <svg width="34" height="34" class="text-pink-500">
                <use xlink:href="#heart-fill"></use>
            </svg>
        </div>
        {% else %}
        <div class="absolute text-white outline-none top-6 right-6 hover:text-pink-500 focus:text-pink-500 add-btn">
            <svg width="34" height="34">
                <use xlink:href="#heart"></use>
            </svg>
        </div>
        {% endif %}
    </button>
</form>
```
@Tam

**Comment by engram-design** [comment]
I'm not seeing any issues in a multi-site system sorry - everything is working as expected with the two lists being independent of each other across sites.

I will note that your markup seems incorrect, with an anchor tag inside a button element - is that correct?

Can you describe what you're seeing on your end? Just the item isn't being added to your list?

**Comment by taher-amici** [comment]
Issue is seems to be sort out using another method. 
Thanks for your response!
