### ISSUE TITLE
Error when running Garbage Collection

### ISSUE THREAD

**Issue by olivierbon** [verbb/wishlist#108]
### Describe the bug

Running `php craft gc` throws:

```
Exception 'Error' with message 'Class "verbb\wishlist\services\Item" not found'

in /var/www/html/vendor/verbb/wishlist/src/services/Lists.php:181
```

### Steps to reproduce

Run `php craft gc`

### Craft CMS version

4.2.5.1

### Plugin version

2.0.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Whoops, thanks @olivierbon !
