### ISSUE TITLE
Add option signature to remove function

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/wishlist#113]
### What are you trying to do?

You can add the same item with a different options object to a wishlist. But there is no way now to remove that item. Removing an item only checks the list and the element ID, but not the option signature.
This means that the first item with the ID is removed from the list, but that could be the wrong one.

There is also not an option signature to check if an item is in a wishlist (to change the layout). So whenever a certain element is in the wishlist, it returns `true` even if it has a different options object.

### What's your proposed solution?

Add an optional options object to these functions similar to the add function.

**Comment by engram-design** [comment]
Yep, good point!

**Comment by TomDeSmet** [comment]
When will 3.0 be released? Because this is kind of an acute issue for us.

**Comment by engram-design** [comment]
Likely not until early next year, sorry.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
