### ISSUE TITLE
Are wishlist_items where elementId is null orphaned whishlist_items? 

### ISSUE THREAD

**Issue by a-am** [verbb/wishlist#115]
### Question

I have a large set of whishlist_items in the database that don't have an elementId.  Would these be considered orphaned or unconnected items? I am trying to determine if I should delete these if they are just taking up space.
In addition are lists orphaned if whishlist_lists userId column is null?

**Comment by engram-design** [comment]
That's correct, they would be considered orphaned. You can run the `./craft wishlist/items/cleanup-orphaned-items` console command to automate this for you.

As for the lists, `userId` being null would be considered guest columns, so that's not really considered as orphaned.
