### ISSUE TITLE
Wishlist items that are no longer Craft elements

### ISSUE THREAD

**Issue by green17** [verbb/wishlist#120]
### Question

We have a large number of wishlists on a website, some of these lists contain elements that are no longer Craft elements. However, these elements are still appearing in some lists and cannot be removed (i.e. user cannot remove them using the remove button). I have checked in the wishlist_items table and it looks like they have an elementId of NULL. Am I right in saying that these are orphaned items? Running the `./craft wishlist/items/cleanup-orphaned-items` command hasn't resolved the issue unfortunately. Locally I was able to resolve the issue by manually deleting the elements from the wishlist_items table, is there a way to do this via the command line?

**Comment by engram-design** [comment]
Correct, these would be orphaned items. I'm not 100% sure why the foreign key retains the Wishlist item, but I'm sure there was a reason for this.

Regardless, you can now run that command to remove those items with `elementId = null`. To get this early, change your `verbb/wishlist` requirement in `composer.json` to:

```
"require": {
  "verbb/wishlist": "dev-craft-4 as 2.0.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by green17** [comment]
Thank you @engram-design the `./craft wishlist/items/cleanup-orphaned-items` command has cleared out the old orphaned items for us.
