### ISSUE TITLE
Eager load wishlist item?

### ISSUE THREAD

**Issue by thisisjamessmith** [verbb/wishlist#124]
### Question

You have the following example code in your docs:

```
{% for entry in craft.entries.section('news').all() %}
    {% set item = craft.wishlist.item(entry.id) %}

    <a href="{{ item.toggleUrl() }}">Toggle</a>
{% endfor %}

```

...However, this causes a set of per-entry queries, which on one of my pages adds 700 queries to the page. Is there any way to eager load this info?

**Comment by engram-design** [comment]
Not at the moment. We plan to [revamp](https://github.com/verbb/wishlist/issues/107) the API to not have this duplicate querying for starters. As for eager-loading, that's not possible at the moment. You can't really eager-load wishlist items from an entry or other element.

**Comment by thisisjamessmith** [comment]
ok, thanks for getting back to me

**Comment by engram-design** [comment]
Updated in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
