### ISSUE TITLE
Craft 3: dompdf dependency

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/wishlist#126]
### Describe the bug

Since Craft Commerce 3.4.21 Dompdf 2.0.0 or later is required, but can't be installed cause this plugin doesn't allow it.

### Steps to reproduce

1. Try updating to Commerce 3.4.21

### Craft CMS version

3.8.13

### Plugin version

1.4.17

**Comment by engram-design** [comment]
Fixed in [1.4.18](https://github.com/verbb/wishlist/releases/tag/1.4.18)
