### ISSUE TITLE
Expose public methods like "getInUserLists" in WishlistVariable.php as services

### ISSUE THREAD

**Issue by Antimated** [verbb/wishlist#127]
### What are you trying to do?

We want to use the functionality of the `getInUserLists` twig variable but we need this data in our own module. Now we have to basically copy [this method](https://github.com/verbb/wishlist/blob/0636b917fa9aeec71af26ae294edca31fb38e9f6/src/variables/WishlistVariable.php#L71) in our own service so we can expose it to the rest of our project.

### What's your proposed solution?

Copy the logic of the public methods in [WishlistVariable.php](https://github.com/verbb/wishlist/blob/craft-4/src/variables/WishlistVariable.php) to a service so we can use these services in our own modules 😄!

**Comment by engram-design** [comment]
Pencilling in as part of a [larger refactor](https://github.com/verbb/wishlist/issues/107)

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
