### ISSUE TITLE
List reference is not refreshed when a list is duplicated in the CMS

### ISSUE THREAD

**Issue by martyspain** [verbb/wishlist#128]
### Describe the bug

When a CP user duplicates a list in the CMS, the new list's `reference` property is not updated to a fresh value but instead keeps the value from the original list. This can cause issues when querying lists by reference.

I would expect the reference to always be unique.

### Steps to reproduce

1. Create a new list, of any type.
2. Edit the list in the CMS and note its `reference` value.
3. Duplicate the list in the element index page, using the standard Craft element action menu.
4. Edit the new duplicate list element and note that its `reference` value is the same as the original list.

### Craft CMS version

4.4.14

### Plugin version

2.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/wishlist:"dev-craft-4 as 2.0.5`

**Comment by engram-design** [comment]
Updated in [2.0.6](https://github.com/verbb/wishlist/releases/tag/2.0.6)
