### ISSUE TITLE
Junk wishlist/Guest wishlist - Craft CMS

### ISSUE THREAD

**Issue by globalizeme** [verbb/wishlist#131]
### Describe the bug

We are facing some issues with the wishlist functionality, we are using this plugin in one of our Craft CMS client websites. The setting on the admin side of the plugin is not working as expected. The Guest wishlist is not clearing after a certain period as per the plugin settings. Due to that, the DB values are stored in high numbers causing High RDS utilization and the website is going down frequently. We need your guidance/assistance to fix the plugin settings so that the empty list & empty guest list will be cleared and DB load should be reduced.
![image](https://github.com/verbb/wishlist/assets/14217852/124b5241-a1c0-452c-be83-9c6900444f78)

### Steps to reproduce

1. 
2. 

### Craft CMS version

3.9.6

### Plugin version

1.4.18

### Multi-site?

No

**Comment by engram-design** [comment]
These settings rely on Craft's garbage collection, so they don't always fire every time, around the clock. I'd recommend firing off a console command on a routine basis using a cron job or similar for more reliable results. You can also run `./craft gc/run` to forge garbage collection to run.

The console command is `./craft wishlist/lists/purge-inactive-lists`
