### ISSUE TITLE
Updating Search Indexes - Typed static property verbb\wishlist\Wishlist::$plugin must not be accessed before initialization

### ISSUE THREAD

**Issue by goodmixer** [verbb/wishlist#132]
### Describe the bug

Since updating to Craft 4 I'm getting multiple warnings of failed items in Queue Manager with the following message Typed static property verbb\wishlist\Wishlist::$plugin must not be accessed before initialization.

Everything seems to be working as expected though.

Running Craft CMS 4.5.13 & Verbb Wishlist 2.0.7

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.5.13

### Plugin version

Wishlist 2.0.7

### Multi-site?

NO

**Comment by engram-design** [comment]
I've seen these errors crop up before, but something is trying to call Wishlist before the plugin has been initialized. It's tricky to pinpoint exactly where this comes from, as it could be triggered by another plugin as well.

Are you able to send through your log files to `support@verbb.io` for us to take a look? We're just interested in the stack trace for the error, to be able to look back on where it's being triggered from. This will likely be in your `/storage/logs/queue.log` file.
