### ISSUE TITLE
Following & Followers Lists

### ISSUE THREAD

**Issue by vonscriptor** [verbb/wishlist#135]
### Question

I'm using Wishlist for users to Follow/Unfollow others. I'd like to show the count (and users) on profiles for Following (count) and Followers (count). Following is straightforward, but how could I query or create a list for Followers?

**Comment by engram-design** [comment]
Are you adding user elements to the wishlists to track users to be able to follow?

If so, you should be able to query based on the item's element, which would be the userId you want to see.

```twig
{# Get all items site-wide that have the userId 1234 in them #}
{% set items = craft.wishlist.items().elementId(1234).all() %}

{% for item in items %}
    {# Show the owner of the list #}
    {{ item.list.user }}
{% endfor %}
```

Does that help?

**Comment by vonscriptor** [comment]
Very helpful! Thank you!
