### ISSUE TITLE
 Table 'db.content' doesn't exist

### ISSUE THREAD

**Issue by Mchei** [verbb/wishlist#136]
### Describe the bug

Hi there,

I just downloaded the Wishlist 3.0 Beta for CraftCMS 5.0.0-RC1, and noticed after I execute 
"<input type="hidden" name="action" value="wishlist/items/add">", and would like to check the list in the admin panel, it is showing: 
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.content' doesn't exist"

I have tried reinstall and use composer to reinstall, still no luck.

### Steps to reproduce

1. Admin Panel
2. Wishlist - Lists
3. Select any List
4. Error shows up.

### Craft CMS version

Craft CMS Pro 5.0.0-RC1

### Plugin version

3.0.0-beta.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.2](https://github.com/verbb/wishlist/releases/tag/3.0.0-beta.2)
