### ISSUE TITLE
Add to cart is not working

### ISSUE THREAD

**Issue by krisMoca** [verbb/wishlist#137]
### Describe the bug

Adding all items from wishlist to cart, adding an item from wishlisting to cart and renaming wishlist list failed - throwing session error.

![image](https://github.com/verbb/wishlist/assets/86084360/0af514a5-ccc8-4112-9185-feb268d88054)

### Steps to reproduce

1. Add an item to wishlist
2. add an item from wishlist to commerce cart.

### Craft CMS version

4.9.4

### Plugin version

2.0.10

### Multi-site?

Yes

**Comment by engram-design** [comment]
Seems to be working for me all okay. This error seems to point to more of a permission issue which was [recently added](https://github.com/verbb/wishlist/commit/48be9ec27aea98da9a92ea05b79e1643003491df) where we don't want to be able to do actions on lists that aren't the users own.

Having said that if this is a list from someone else that's going to be an issue.

Should be fixed for the next release. To get this early, run `composer require verbb/wishlist:"dev-craft-4 as 2.0.10"`.

**Comment by engram-design** [comment]
Fixed in [2.0.11](https://github.com/verbb/wishlist/releases/tag/2.0.11)
