### ISSUE TITLE
Customise default title when creating a playlist

### ISSUE THREAD

**Issue by johndwells** [verbb/wishlist#145]
### What are you trying to do?

We are using Wishlist to allow users to build playlists, similar to Youtube. We've designed the UI such that when a user has no lists, we _fake_ one so that the user doesn't have to create it first. We have built some custom endpoints through a custom module to accomplish much of this.

So we have an endpoint that accepts `listId` as a payload parameter, which we then use to fetch the list like so:

```
$listId = $request->getParam('listId');
$listTypeHandle = $request->getParam('listTypeHandle');
...
$list = Wishlist::$plugin->getLists()->getList($listId, true, $listTypeId);
```

The 2nd parameter `true` is `forceSave`. This will create a new list if `$listId` is `null`. This is great, it all works lovely.

When the new list is created, it's given a name based on the list type's name. This is the behaviour I would like to change.

We would love the ability to override the default title for new playlists that are created in this way.

### What's your proposed solution?

Add a "Default Playlist Name" configuration to editing a List Type. If blank, will use the List Type's name (current behaviour).

**Comment by engram-design** [comment]
Sounds like this is for Wishlist 2 for Craft 4? Wishlist 3 for Craft 5 does change this behaviour a bit.

This could probably be achieved using an [event](https://verbb.io/craft-plugins/wishlist/docs/v2/developers/events#the-beforeSaveList-event):

```
use craft\events\ModelEvent;
use verbb\wishlist\elements\ListElement;
use yii\base\Event;

Event::on(ListElement::class, ListElement::EVENT_BEFORE_SAVE, function(ModelEvent $event) {
    if ($event->isNew) {
        $event->sender->title = 'My Custom Title';
    }
});
```

**Comment by johndwells** [comment]
Perfect! I should have thought of that myself. Thanks Josh!
