### ISSUE TITLE
Admin user permissions not working

### ISSUE THREAD

**Issue by jckvnr** [verbb/wishlist#18]
### Description

When logged in as a non-admin user who has been given permissions to access wishlists, they are not able to open individual wishlists. They get the following error: "User is not permitted to perform this action". Also, they are able to Manage List Types even if they haven't been given permissions.

### Steps to reproduce

1. Login as non-admin user with permissions to access wishlists
2. Go to admin/wishlist/lists
3. Click on a list to view it e.g. admin/wishlist/lists/1234

### Additional info

- Plugin version: 1 or 1.0.1
- Craft version: 3.0.37

**Comment by engram-design** [comment]
Fixed in [1.0.2](https://github.com/verbb/wishlist/releases/tag/1.0.2)
