### ISSUE TITLE
Feature Request - email regarding update to a subscribed entry

### ISSUE THREAD

**Issue by jacksoncool** [verbb/wishlist#2]
### Description
Allow users to receive an email when an entry they have "listed" is updated. Also, provide site user/editor/etc.,  with an option to notify subscribed users or NOT notify subscribed users of an update to a specific entry. 

### Steps to reproduce

1.
2.

### Additional info

- Plugin version:
- Craft version:

**Comment by engram-design** [comment]
I'm going to close this as I think it's a tad beyond the scope of this plugin - although it would be pretty handy to have. I believe that Wishlist as a plugin should facilitate the storing of the "things" you want to keep. When those things update, I believe that should be done as a separate thing. There's also more complexity here with subscribing, and allowing users to manage that.

But - if enough people request this behaviour, I'm very open to adding it. It just seems a little bit niche to my eyes.

**Comment by jacksoncool** [comment]
I would love to have this feature. It's definitely a need for my project.
