### ISSUE TITLE
Problem with multiple lists

### ISSUE THREAD

**Issue by milanjandric** [verbb/wishlist#29]
### Description
There is a problem when using multiple lists. 
I have two types of lists per user. 
1. default - wishlist
2. lastViewedProducts

Products are always added to the second list (last-viewed-products).
The service https://github.com/verbb/wishlist/blob/craft-3/src/services/Lists.php#L44
caches the first accessed list and returns it regardless of the listType. 

### Steps to reproduce
$listType = Wishlist::$plugin->listTypes->getListTypeByHandle('lastViewedProducts');
$lastViewedProductsListForCurrentUser = Wishlist::$plugin->lists->getList(null, false,$listType->id );

$listType = Wishlist::$plugin->listTypes->getListTypeByHandle('wishlist');
$wishListForCurrentUser = Wishlist::$plugin->lists->getList(null, false,$listType->id );  //not true. lastViewedProductsListForCurrentUser is returned.

So the solution would be either not to cache at all or to cache in a map listType=>List 
Or a method call to force invalidation of the cache. 
### Additional info

- Plugin version: 1.0.6

**Comment by engram-design** [comment]
Fixed in [1.1.0](https://github.com/verbb/wishlist/releases/tag/1.1.0)
