### ISSUE TITLE
Feature Request - separate purge times for guest and authenticated user's lists

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/wishlist#33]
Hi

Would it be possible to implement something to allow different periods for purging guest lists vs authenticated user's lists?

My situation is that my users might only visit the site very occasionally, but still expect their wishlist to be there when they log back in - perhaps after a few months or more. But equally I don't want to let guest lists to hang around that long.

It would be really nice to be able to set a purge time of a few days for guest lists, but keep the "real" lists for far longer.

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/wishlist/releases/tag/1.1.0). See [docs](https://verbb.io/craft-plugins/wishlist/docs/get-started/configuration)
