### ISSUE TITLE
craft.wishlist.item(elementId, listId) doesn't work when listId is passed.

### ISSUE THREAD

**Issue by whoisjuan** [verbb/wishlist#34]
### Description

When I do `craft.wishlist.item(elementId, listId)` and provide a specific listId no valid object is returned although I'm certain that particular element exists in that particular list.

### Steps to reproduce

1.  Query an item by providing a specific list id where that item is stored `craft.wishlist.item(elementId, listId)`

2. No valid object is returned, although the item exists in that list.

### Workaround

This works though:

```
{% set currentItemExists = craft.wishlist.items
         .elementID(entry.id)
         .listId(list.id)
          .all()
%}
```

So maybe update "Available Variables" documentation to favor this method and/or deprecate the ability of passing `listId` in `craft.wishlist.item`

**Comment by engram-design** [comment]
Fixed in [1.1.0](https://github.com/verbb/wishlist/releases/tag/1.1.0)
