### ISSUE TITLE
Search indexing queue task fails with Wishlist error 

### ISSUE THREAD

**Issue by martyspain** [verbb/wishlist#36]
In my production environment, all of my 'Updating search indexes' tasks are failing with the following error:

`Getting unknown property: verbb\wishlist\elements\Item::ticketSku`

Do you have any idea why this might be happening?

**Comment by ghost** [comment]
I get this too, on my local environment.

**Comment by engram-design** [comment]
Fixed in [1.1.1](https://github.com/verbb/wishlist/releases/tag/1.1.1), sorry about that.
