### ISSUE TITLE
Frontend edit of disabled list 

### ISSUE THREAD

**Issue by ghost** [verbb/wishlist#37]
### Description
I can list, add and delete elements, delete or edit the list if it is disabled.
But i can't empty list, or add elements to Cart when it is disabled.
Is this a bug or is it intended behaviour?

The user can disable lists to make them private. So the user can share public lists but not the private ones. Any other solutions to this is welcome :)

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.3.15

**Comment by engram-design** [comment]
This is sort of intended behaviour, but its also not overly clear. I wouldn't want to change behaviour suddenly, so I've added a `manageDisabledLists` config setting, that's default to true. This will allow all actions to be undertaken on lists and items, unless you turn this off.

Added in [1.2.1](https://github.com/verbb/wishlist/releases/tag/1.2.1).
