### ISSUE TITLE
Clear/Delete list link controller

### ISSUE THREAD

**Issue by bymayo** [verbb/wishlist#38]
It would be good if you could do the clear / delete list actions as links, similar to how you can add / remove items. Currently in the docs it's only possible as a form (https://verbb.io/craft-plugins/wishlist/docs/template-guides/managing-lists#clear-list)

I did try:

```
<a href="{{ actionUrl('wishlist/lists/delete', { listId: list.id }) }}">
    Delete
</a>
```

But I got an error:

```
Request missing required param

public function actionClear()
    {
        $request = Craft::$app->getRequest();
        $listId = $request->getRequiredParam('listId');
 
        $list = ListElement::findOne($listId);

...
```

I'm using the `actionUrl` helper like above and it generates:

https://website.com/index.php?p=actions/wishlist/lists/clear&listId=215462

**Comment by engram-design** [comment]
Added in [1.2.1](https://github.com/verbb/wishlist/releases/tag/1.2.1), what you were doing was correct FYI

**Comment by bymayo** [comment]
@engram-design Thanks for looking at this, do I need Craft 3.4.x to update to this version?

**Comment by engram-design** [comment]
Yep, only on the 3.4.x version, but I can back-track it if its critical?

**Comment by bymayo** [comment]
@engram-design How difficult is it to back-track? 

We basically just did a Craft 2 > Craft 3 upgrade the day before 3.4 was released! Which included moving from Shortlist > Wishlist.  We don't want to scare the client a day later with 3.4 as that's again another big change in the CMS (With the new styles etc).

Not to mention other compatibility issues.

**Comment by bymayo** [comment]
@engram-design Scratch that. We took the plunge and upgraded to 3.4! Eeep.
