### ISSUE TITLE
wishlist plugin breaks project-config/rebuild

### ISSUE THREAD

**Issue by ghost** [verbb/wishlist#39]
### Description
Found a bug when i noticed that changes to my config file didn't sync.
Don't know if this is fixed in 1.2, but we cant update to 3.4 yet.
Is it possible to get a hotfix for 1.1.1?

### Steps to reproduce

1. run `./craft project-config/rebuild` in console
2. gets `Rebuilding the project config from the current state ... error: Argument 1 passed to verbb\wishlist\Wishlist::verbb\wishlist\{closure}() must be an instance of verbb\wishlist\RebuildConfigEvent, instance of craft\events\RebuildConfigEvent given`

### Additional info

- Plugin version: 1.1.1
- Craft version: 3.3.15

**Comment by engram-design** [comment]
No problem, fixed in [1.1.2](https://github.com/verbb/wishlist/releases/tag/1.1.2) for Craft 3.0-3.3
