### ISSUE TITLE
Feature Request - store guest wishlists using cookie

### ISSUE THREAD

**Issue by j-greig** [verbb/wishlist#4]
Allow guest users to close their browser and return the next hour or day and still have access to their wishlist. 

(Something that worked with https://github.com/nystudio107/craft-cookies maybe?)

**Comment by putyourlightson** [comment]
This seems like a key feature, thumbs up!

**Comment by DanielDarrenJones** [comment]
+1 For this

**Comment by engram-design** [comment]
Not sure if this is possible, as cookie size limits (4kb) will likely come into play here. localStorage might be the option here.

**Comment by bencroker** [comment]
Storing element IDs in cookies should be relatively safe I would think...?

**Comment by engram-design** [comment]
I suppose, if we're talking about storing the wishlist item element IDs. Depends how many different lists to store, and how many items to be stored in each

**Comment by j-greig** [comment]
localStorage actually sounds good to me, it's a lot easier to work with

**Comment by engram-design** [comment]
I'll need to do some testing here, cookies can be used server-side, which is handy for us (re-creating the guest's list when they come back), but I don't want to back myself into a corner. Especially if I want to add [extra options](https://github.com/verbb/wishlist/issues/21) with items - it can no longer be just the Wishlist item's element ID that's stored in the cookie.

At the moment, it's looking like localStorage, with maybe some front-end JS to make it happen.

**Comment by engram-design** [comment]
I'm very pleased to announce this is now added as default behaviour in [1.3.0](https://github.com/verbb/wishlist/releases/tag/1.3.0)

I also believe this will help a reasonable amount with your site's lists getting out of control. Under the hood, the sessionId, generated for every user is saved in a cookie - whether you're logged in or not. So even shutting down the browser and loading up the site again will persist all the user's lists.

Whereas before, if you shut down your browser and opened it again, a new list would be created.

**Comment by j-greig** [comment]
Sounds awesome, thank you ✌️

**Comment by outline4** [comment]
Hi, in the docs I still read "_Lists are session-based, and are populated as long as the current session is active. For guests, as soon as their session ends – such as they close their browser – their list items will be gone. For registered and logged-in users, lists will be persisted against their account, so It's important to prompt your users to log in or register to save their list contents. In fact, it works pretty similar to a typical Cart!_" 

This this really get implemented? 

If yes: thanks a lot!

Please update the docs...

**Comment by engram-design** [comment]
Yep, docs just out of date!

**Comment by outline4** [comment]
ok, thanks for clarifying!
