### ISSUE TITLE
Shortlist import

### ISSUE THREAD

**Issue by bymayo** [verbb/wishlist#40]
I know a lot of developers coming from Craft 2 > Craft 3 will have used Shortlist plugin.

It would be good if there was a way to import these when doing the upgrade.

**Comment by bymayo** [comment]
Bit of background on this, I found that it was quite easy to do manually by just changing the `type` in `elements` from `Shortlist_List` to `verbb\wishlist\elements\ListElement` and `Shortlist_Item` to `verbb\wishlist\elements\Item`.

Then it was just a case of copying across the table data from `shortlist_item` to `wishlist_items`, which is very similar! And the same for `shortlist_list` to `wishlist_lists`, again very similar! The tricky bit being the `reference`  on the lists.

```
SELECT 
	id,
	CONCAT('sl-', SUBSTRING(`hash`, 1, 7)) as 'reference',
	ownerId as 'userId',
	'1' as typeId,
	dateCreated,
	dateUpdated,
	uid
FROM
	craft_shortlist_list 
WHERE 
	ownerId REGEXP '^[0-9]+$';
```

```
SELECT 
	item.id,
	item.elementId,
	item.listId,
	"craft\\elements\\Entry" as 'elementClass',
	'1' as elementSiteId,
	item.dateCreated,
	item.dateUpdated,
	item.uid
FROM
	craft_shortlist_item item
INNER JOIN
	craft_elements elements on elements.id = item.elementId
INNER JOIN 
	craft_wishlist_lists lists on item.listId = lists.id
```

**Comment by engram-design** [comment]
Nice work @bymayo - its on my todo list as that was the main reason for this plugin to be created (moving clients over from Craft 2 + Shortlist). We tried to keep things pretty similar for this reason.

This might be handy for people in the meantime

**Comment by bymayo** [comment]
@engram-design Yeah this should help anyone out in the interim! This code only copies across logged in user lists, not guest lists also. We just scrapped them.

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/wishlist/releases/tag/1.3.0)
