### ISSUE TITLE
[Docs] Adding product variants

### ISSUE THREAD

**Issue by bymayo** [verbb/wishlist#41]
I know this is more of a request for a change in the docs, but it might be worth showing how to add products to a wishlist, to then use the add to cart function (https://verbb.io/craft-plugins/wishlist/docs/template-guides/add-to-cart)

I was initially adding the product to the wishlist, but this then wouldn't add it to the cart as the product wasn't the purchasable. Instead I realised you add the product variant to the wishlist and it intelligently grabs the name of the product.

Maybe a section just for commerce in your docs would be great.

On the flip side, now I've got it working it works a charm!

**Comment by bymayo** [comment]
Also, it would be good if the variant thats added also appears in the admin table when looking inside a wishlist. Because if you add 6 of the same products, but all with different variants it does this:

Item        | Type
---------|--------
Product A | Product Variant 
Product A | Product Variant
Product A | Product Variant
Product B | Product Variant

Where it would be good to know:

Item | Type | Variant
--- |--- | ---
Product A | Product Variant | Green
Product A | Product Variant | Blue
Product A | Product Variant | Red
Product B | Product Variant | Red

**Comment by engram-design** [comment]
Adding any element (entry, category, product, variant) is all the same. Would docs with examples for each help? I have updated the docs to include that as a first step.

Not quite sure I follow you on your second point. When adding a variant, that'll appear in the "List Items" table when you view the contents of a wishlist? For instance - https://d.pr/free/i/Uq7YJM

The title for the item should be the variant's title, not the product title. The screenshot above shows the standard Commerce products (which are a single-variant), but also a "Blue" variant, which is a single variant from a product "T-Shirt"

**Comment by bymayo** [comment]
> Adding any element (entry, category, product, variant) is all the same. Would docs with examples for each help? I have updated the docs to include that as a first step.

Yeah I think an example for each would be good, if they are different. It was mainly understanding how the variants got added, as I originally was adding products to the wishlist, not variants.

What you've added though now is a really big help.

> The title for the item should be the variant's title, not the product title. The screenshot above shows the standard Commerce products (which are a single-variant), but also a "Blue" variant, which is a single variant from a product "T-Shirt"

Okay, I didn't realise this, it was mainly because I was using products with only 1 variant to test. Doh. So if there is multiple variants assigned to a product, it will show the variant in the `Title` column?

**Comment by engram-design** [comment]
Yep, was kinda missing that first step of adding **variants** to your lists - thanks!

And that's correct. That column will use the `title` attribute of any element that's added.

**Comment by bymayo** [comment]
Perfect! Case closed.
