### ISSUE TITLE
Error on craft's search index refresh

### ISSUE THREAD

**Issue by lexislav** [verbb/wishlist#44]
### Description

When craft auomaticly refresh search indexes, I am getting those errors in action gueue:

{
    "elementType": "verbb\\wishlist\\elements\\Item",
    "elementId": 82631, // this changes of course
    "siteId": "1",
    "fieldHandles": [],
    "description": null
}

The plugin is set to erase the lists, so maybe the list doesn exist in the moment of search index refresh?

- Plugin version: 1.2.6
- Craft version: Craft Pro 3.4.17.1
- plugin settings:

`return [
    '*' => [
        'pluginName' => 'Rent list',
        'allowDuplicates' => false,
        'manageDisabledLists' => true,
        'mergeLastListOnLogin' => true,
        'purgeInactiveLists' => true,
        'purgeInactiveListsDuration' => 'P5D',
        'purgeInactiveGuestListsDuration' => 'P1D', // 1 day
    ]
];`

**Comment by engram-design** [comment]
Can you send through the full error from the queue? There should be an error message stating what the specific error is. From your description, its hard to tell what the issues is...

**Comment by howells** [comment]
I have the same problem, and the error in the logs is: "Invalid list ID: xxxx" presumably because by the time the job is run, the list has subsequently been changed/removed etc.

**Comment by engram-design** [comment]
Fixed in [1.2.9](https://github.com/verbb/wishlist/releases/tag/1.2.9)
