### ISSUE TITLE
mergeLastListOnLogin should be set to false by default

### ISSUE THREAD

**Issue by martyspain** [verbb/wishlist#46]
When a user with existing lists logs into their account, they will have all of their lists merged into the oldest list that they have, whether they want that to happen or not.

This is caused by the `mergeLastListOnLogin` config setting, which is set to `true` by default. I feel like this is a pretty powerful config setting and should probably be `false` by default instead, because it can have a huge effect on existing installs of Wishlist. Our user base have had all of their carefully crafted lists merged into one without us realising it was happening.

### Additional info

- Plugin version: 1.2.9
- Craft version: 3.4.19.1

**Comment by engram-design** [comment]
Good point, I think the customer I was assisting at the time wanted this, and didn't see a reason why it wouldn't be helpful. In hindsight, I do agree with your point.

Updated in [1.2.10](https://github.com/verbb/wishlist/releases/tag/1.2.10)
