### ISSUE TITLE
Return Item ID in JSON in Add action

### ISSUE THREAD

**Issue by mheob** [verbb/wishlist#47]
### Description

In addition to #45, it would be nice to get the itemID back after firing the add action.

### Steps to reproduce

I use the fetch method to add a new item with any quantity to a list.
```js
const response = await fetch('/', {
  method: 'POST',
  body: formData, /* includes the add action etc. */
  headers: {
    Accept: 'application/json'
  }
});
const data = await response.json();
console.log(data);
```
The response is:
```js
{action: "add", success: true}
```
Then I directly change the quantity, but at this point I don't know the ItemID, so I can't include it and get an error. The response is:
```js
{action: "update", error: "Item ID must be provided."}
```
After a page reload I get the ID from the twig template and everything is fine. But unfortunately it is not possible to use it with AJAX like this.

### Additional info

- Plugin version: 1.2.10
- Craft version: 3.4.20

**Comment by engram-design** [comment]
Added in [1.2.11](https://github.com/verbb/wishlist/releases/tag/1.2.11)
