### ISSUE TITLE
Include item model in toggle action AJAX response

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/wishlist#49]
### Description

In the same way the item model was added to the add/remove actions (#47) it would be good if the `item` model was also returned in the AJAX response from the toggle action or just the source element ID (Entry, Category etc).

### Additional info

- Plugin version: 1.2.12

**Comment by engram-design** [comment]
Fixed in [1.2.13](https://github.com/verbb/wishlist/releases/tag/1.2.13).

Please take note of the new deprecations however, and adjust your JS accordingly.
