### ISSUE TITLE
FR: Return list reference on wishlist/lists/create action

### ISSUE THREAD

**Issue by BrandonJamesBorders** [verbb/wishlist#51]
### Description
When creating a list via Ajax, reference is not passed back in the JSON response.
![image](https://user-images.githubusercontent.com/6044898/85813006-1f51f700-b730-11ea-9b48-ae1ef1643c7e.png)

### Additional info
I'm creating a complete AJAX flow of adding items to "wishlists" like you would add songs to a playlist in Spotify. The user clicks "Add to list" and the user is displayed a list of lists they already created and the ability to create a new list. After they do either, I display a message saying the item has been added and they can view their list at this URL, which utilizes the reference number. I have the reference number if they select a previously created list, but not the reference number for the new list. 

- Plugin version: 1.2.14
- Craft version: 3.4.24

**Comment by engram-design** [comment]
Added in [1.2.15](https://github.com/verbb/wishlist/releases/tag/1.2.15) - thanks again!
