### ISSUE TITLE
Clear List 

### ISSUE THREAD

**Issue by Simon-00** [verbb/wishlist#57]
**Description**
It seems that the clear list feature is broken?
I'm logged in as admin in the control panel. Applied the example code for clearing a list to the frontend.

**Steps to reproduce**
1. Adding the example code for clearing a list to the frontend
2. Sending the form
3. Error gets thrown: _You can only clear your own list._

**Additional info**
- Plugin version: 1.2.16
- Craft version: 3.5.5
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [1.2.17](https://github.com/verbb/wishlist/releases/tag/1.2.17)
