### ISSUE TITLE
Adding to non-default wishlist that doesn't exist yet

### ISSUE THREAD

**Issue by jckvnr** [verbb/wishlist#6]
How do you add an entry to a **non-default** Wishlist if it doesn't exist yet (so no listId)?
Can we pass the list typeId or handle?
Or do we need to somehow create the list and add the entry at the same time?

**Comment by engram-design** [comment]
That's a great point - currently its not possible, which is certainly a bit of an oversight. I'll provide an update soon.

**Comment by jckvnr** [comment]
Thanks mate  - is it an easy enough update, or will it be a while away?
If so, do you have a suggested workaround for the moment (perhaps creating the list when they activate their account or something)?
We're putting that furniture site live in a few days, which now uses Wishlist extensively - will be a great example of it in action - such an awesome plugin, thanks again.

**Comment by engram-design** [comment]
Added in [1.0.1](https://github.com/verbb/wishlist/releases/tag/1.0.1) (thanks @echantigny for your PR). Achieved via passing in the listTypeHandle:

```
<input type="text" name="listTypeHandle" value="favourites">
```
