### ISSUE TITLE
Add ability to display additional fields to list item element index within admin

### ISSUE THREAD

**Issue by jckvnr** [verbb/wishlist#60]
**What are you trying to do?**
In the admin, when viewing a list and its list items, would be useful to be able to choose the element index columns to display additional fields.

**What's your proposed solution?**
Same functionality as element index for entries, or edit in config similar to Element Index Defaults Plugin.

**Comment by engram-design** [comment]
Yeah, this is tricky. Would you be okay with having this controlled at the list type level? You wouldn't be able to customise it per list, but I figure you'd also not necessarily want that (every time you look at a list, you need to toggle the columns).

The only difference would be that it's not customisable per-user.

The current way of managing element index columns is pretty heavily tied to the element index view I believe.

**Comment by engram-design** [comment]
Actually, ended up figuring out a way to do this natively. Added in [1.3.0](https://github.com/verbb/wishlist/releases/tag/1.3.0)
