### ISSUE TITLE
migrated from C2 Shortlist to C3 Wishlist - duplicated empty list handles being created

### ISSUE THREAD

**Issue by tonyclemmey** [verbb/wishlist#62]
**Description**

Migration from C2 Shortlist to C3 Wishlist - list entries seem to be created for the default or first list type handle (empty / 0 items) as well as the correct list type handle being created and items added to it. So it is sort of a duplicated entry in some aspect but just empty.

Example of List Types added in the control panel;

Name = Wishlist, Handle = wishlist (default or first)
Name = My List A, Handle = myListA
Name = My List B, Handle = myListB
Name = My List C, Handle = myListC

TWIG Code

```
{# Set the title/handle #}
{% set v_assetListTitle = "myListA" %}

{% set v_assetList = [] %}
{% set v_assetListId = null %}
{% set v_assetListItems = [] %}

{# Look for existing list match #}
{% if craft.wishlist is defined %}
    {% for list in craft.wishlist.lists %}
        {% if list.type == v_assetListTitle %}
            {% set v_assetList = list %}
            {% set v_assetListId = list.id %}
            {% set v_assetListItems = list.items %}
        {% endif %}
    {% endfor %}
{% endif %}

{% if craft.wishlist is defined and v_assetListTitle is not null %}
    {% set item = craft.wishlist.item(asset.id) %}
    {% if v_assetListId is not null %}
        {% set isInList = false %}
        {% for item in v_assetListItems %}
            {% if item.elementId == asset.id %}
                {% set isInList = true %}
            {% endif %}
        {% endfor %}

        {% if isInList %}
            {# Remove from exit list #}
            <a class="asset-list-entry-chbx checked" href="{{ item.removeUrl({ listId: v_assetListId }) }}">
              {{ 'Remove from collection' | t }}
            </a>
        {% else %}
            {# Add to exit list #}
            <a class="asset-list-entry-chbx" href="{{ item.addUrl({ elementId: asset.id, listId: v_assetListId }) }}">
              {{ 'Add to collection' | t }}
            </a>
        {% endif %}
    {% else %}
    	{# Add to new list #}
        <a class="asset-list-entry-chbx" href="{{ item.addUrl({ elementId: asset.id, listTypeHandle: v_assetListTitle }) }}">
          {{ 'Add to collection' | t }}
        </a>
    {% endif %}
{% endif %}
```

Items will be added or removed from the correct list handle but at the same time, empty entries are added for the default or first handle.

**Steps to reproduce**
1. Set multiple list handles (keep the first or default as `wishlist` for example)
2. Set a template to add or remove from a non-default or 2nd /3rd list handle ( `see code above` )
3. Items are added to the correct set handle, but an entry for the default or first handle is also created but empty.

**Additional info**
- Plugin version: 1.4.1
- Craft version: 3.5.8
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
I've just setup your test case, with a fresh install, so no lists or items. Not sure if that's an issue.

I modified your template to include `{{ 'Add to collection ' ~ v_assetListTitle | t }}` for clarity of which list we're adding to.

The behaviour I'm seeing is that the item is being added and removed from "My List A" - no other list is being affected.

![Screen Shot 2020-12-15 at 3 56 00 pm](https://user-images.githubusercontent.com/1221575/102172948-0ca1c900-3eee-11eb-8356-2c26c5531fed.png)

Am I maybe doing something wrong?

**Comment by tonyclemmey** [comment]
I think this is similar to another listed issue here https://github.com/verbb/wishlist/issues/24

**Comment by tonyclemmey** [comment]
Hey @engram-design 

Sorry, the delay in coming back to this.

Yes, it's very strange that the item will add to the correct named wishlist "v_assetListTitle" but still, an empty record for the default or first wishlist named "wishlist" is also created for me.

If you have used the same template code then I can only assume it is correct and the issue lies elsewhere 

I am sharing my wishlist config file also in case of anything in it which could be the cause.

```
<?php

return [
    '*' => [
        'pluginName' => 'Collections',
        'showListInfoTab' => true,

        // Lists
        'allowDuplicates' => false,
        'manageDisabledLists' => true,
        'mergeLastListOnLogin' => false,
        'purgeInactiveLists' => true,
        'purgeInactiveListsDuration' => 'P1M', // 3 months, swapped to 1 min for test
        'purgeInactiveGuestListsDuration' => 'P1M', // 1 day, swapped 1 min for test
        'purgeEmptyListsOnly' => true,
        'purgeEmptyGuestListsOnly' => true,
        'cookieExpiry' => 'P1Y', // 1 year

        // PDF
        'pdfFilenameFormat' => 'Wishlist-{id}',
        'pdfPath' => '_pdf/wishlist',
        'pdfAllowRemoteImages' => false,
        'pdfPaperSize' => 'letter',
        'pdfPaperOrientation' => 'portrait',
    ]
];
```
