### ISSUE TITLE
Wishlist on user lists logged in user list

### ISSUE THREAD

**Issue by espensgr** [verbb/wishlist#63]
**Description**
When i go to the tab on a user to see what list that user has, i get the lists of the user i'm logged in with.
The title of the content also seems to be `{{currentUser.fullname}} Wishlist’s` or something like that.

**Steps to reproduce**
1. Go to a user
2. Press the tab: Wishlist

**Additional info**
- Plugin version: 1.3.1
- Craft version: 3.5.13.2
- Multi-site: Yes

**Additional context**
I haven't updated to the latest plugin version yet, but i don't see any mention of this bug, so i guess it's still there.

**Comment by engram-design** [comment]
Yep, correct this is an issue. Fixed in [1.4.3](https://github.com/verbb/wishlist/releases/tag/1.4.3)
