### ISSUE TITLE
Remove from wishlist when adding all items to cart

### ISSUE THREAD

**Issue by russback** [verbb/wishlist#65]
**What are you trying to do?**
You can opt to remove a single item from a list when it's added to cart but not when you add the whole list.

**What's your proposed solution?**
Update the add to cart controller to remove all items from a list if a field named `removeAlllFromList` has a value of `true`.

**Comment by engram-design** [comment]
You can do this using [`clearList`](https://verbb.io/craft-plugins/wishlist/docs/template-guides/add-to-cart#removing-from-list)
