### ISSUE TITLE
Add support for custom template for "share list by email"

### ISSUE THREAD

**Issue by russback** [verbb/wishlist#67]
**What are you trying to do?**
Create a template for the share wishlist email.

**What's your proposed solution?**
Add a config property for a template path. This would enable a developer to bulld whatever email they want, using a list ID or reference passed to the template from the `actionShareByEmail` controller method.

Additionally, paths for HTML and text variations would enable a developer to define the content for both variations.

**Comment by engram-design** [comment]
I should mention you can modify the content of the email going to Utilities > System Messages. But yes, you are reliant on the global email template defined in Settings > Email.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
