### ISSUE TITLE
Pass Commerce variant options when adding list to cart

### ISSUE THREAD

**Issue by russback** [verbb/wishlist#68]
**What are you trying to do?**
I am storing variant options on the list in custom fields, and then when adding an individual item to the list, passing those field values as variant options to the cart:

```
{% set fields = craft.fields.getFieldsByGroupId(5) %}
{% for field in fields %}
  {% if field.handle != 'qty' %}
    <input type="hidden" name="purchasables[{{ item.id }}][options][{{ field.handle }}]" value="{{ item[field.handle] }}">
  {% endif %}
{% endfor %}
```

That works fine, but when you add the whole list to cart, you obviously don't get that behaviour.

**What's your proposed solution?**
Enable an option on the `wishlist/lists/add-to-cart` method to include all fields from the wishlist config.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
