### ISSUE TITLE
Order by an entry's favorite status

### ISSUE THREAD

**Issue by challahan** [verbb/wishlist#69]
I am attempting to output a paginated list of entries (in this case Craft Commerce products) and would like to output the ones that are favorites first, with the non-favorited ones to follow.

I have this partially by doing an IF statement to see if an entry is a favorite first, and then displaying the rest of the entries that are not favorites. Here's that code:

```
{% set list = craft.wishlist.lists().default(true).one() %}

{# Output items in favorites first #}
{% for item in products %}
      {% if list %}
        {% set favorite = craft.wishlist.item(item.id) %}
             {% if favorite.inList %}
                {{ item.title }}
             {% endif %}
       {% endif %}
{% endfor %}

{# Output remaining items NOT in favorites #}
{% for item in products %}
      {% if list %}
        {% set favorite = craft.wishlist.item(item.id) %}
              {% if not favorite.inList %}
                {{ item.title }}
             {% endif %}
       {% endif %}
{% endfor %}

```

This works on a per page basis, but favorited items on page 2, for example, do not appear on page one.

Is there any way I can utilize orderBy instead for a more efficient approach to ordering by favorited/unfavorited items in a paginated list? Any insight is appreciated!

**Comment by engram-design** [comment]
It's not really possible to use `orderBy` in this context, mostly because you're doing a `craft.products.all()` query, and that query needs to know about Wishlist's functionality when whether it's in a list - which it doesn't know anything about. We don't have control over this query of elements.

One option, which might be a little advanced, is to build a collection of products is a particular order, and then paginate through that. The following is untested, but I think it _should_ work.

```
{% set list = craft.wishlist.lists().default(true).one() %}
{% set orderedProducts = [] %}

{# Output items in favorites first #}
{% for item in products %}
      {% if list %}
        {% set favorite = craft.wishlist.item(item.id) %}
             {% if favorite.inList %}
                {% set orderedProducts = orderedProducts | merge([item]) %}
             {% endif %}
       {% endif %}
{% endfor %}

{# Output remaining items NOT in favorites #}
{% for item in products %}
      {% if list %}
        {% set favorite = craft.wishlist.item(item.id) %}
              {% if not favorite.inList %}
                {% set orderedProducts = orderedProducts | merge([item]) %}
             {% endif %}
       {% endif %}
{% endfor %}


{% set resultsDataProvider = create({
    class: 'yii\\data\\ArrayDataProvider',
    allModels: orderedProducts,
    pagination: { pageSize: 10 },
}) %}

{% set results = resultsDataProvider.getModels() %}
{% set currentPage = resultsDataProvider.getPagination().getPage() + 1 %}
{% set pageCount = resultsDataProvider.getPagination().getPageCount() %}

{% for result in results %}
    {{ result.title }}
{% endfor %}
```

It's incredibly verbose, but I can't think of a better way to handle this at the moment...
