### ISSUE TITLE
How to stop search indexing when item is added in the wishlist

### ISSUE THREAD

**Issue by chandamotiyani** [verbb/wishlist#72]
When I add the item to the wishlist I see that the `searchindex` table records increased by 4 to 6 records each time and for cart there is a setting `'updateCartSearchIndexes' => false` which stops cart to be indexed and we want to have the same thing and how to do it for wishlists?

**Comment by engram-design** [comment]
The problem with this, is that then you won't be able to search in lists for Wishlist items in the control panel. So long as you're happy with that, I can introduce this setting.

**Comment by chandamotiyani** [comment]
Yes please, if it's not there then when can we have that feature?

**Comment by chandamotiyani** [comment]
@engram-design can you please give us the approximate time it will take so that by that time we come up with some other solution?

**Comment by engram-design** [comment]
Added `updateListSearchIndexes` and `updateItemSearchIndexes`.

To get this early, change your `verbb/wishlist` requirement in `composer.json` to:

```
"require": {
  "verbb/wishlist": "dev-craft-3 as 1.4.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by chandamotiyani** [comment]
@engram-design Thank you very much, appreciate it :+1::clap:

**Comment by engram-design** [comment]
Added in [1.4.4](https://github.com/verbb/wishlist/releases/tag/1.4.4)
