### ISSUE TITLE
Items not retained after login and logout

### ISSUE THREAD

**Issue by engram-design** [verbb/wishlist#73]
TEST 1

add products to wishlist as guest
join as an insider
the products you had added to wishlist as a guest should still be in your wishlist after signing up
discounts should show
TEST 2
log in as an existing user; do you still have products in your wishlist

TEST 2 is not working in both versions of the wishlist plugin 1.4.3 and 1.4.4

I add items as a guest user and sign up then I'm able to see the items post login in my wish list but when I logout and re-login back again wish list is empty. Even If I add items as a logged-in user and logout and re-login back again wishlist is empty again.

**Comment by engram-design** [comment]
@chandamotiyani I can't seem to replicate this behaviour. Everything sounds like it's working, as guest items/lists are being migrated to the logged-in user correctly. Logging in and out shouldn't do anything.

What I think might be happening is that you have an existing wishlist on that user account already, and you've created a new one as a guest. You need to instruct Wishlist to merge your existing wishlists when you login. You can do this with the `mergeLastListOnLogin` config setting - https://verbb.io/craft-plugins/wishlist/docs/get-started/configuration

**Comment by engram-design** [comment]
To illustrate without this setting turned on, I add an item to the wishlist as a guest:

![image](https://user-images.githubusercontent.com/1221575/106080729-c1750a00-616b-11eb-87b3-f4f3331b34fa.png)

Then login:

![image](https://user-images.githubusercontent.com/1221575/106080757-cdf96280-616b-11eb-905a-55559dce32cc.png)

Then logout and add another item to my list. It creates a new list, because we're a guest.

![image](https://user-images.githubusercontent.com/1221575/106080823-e9646d80-616b-11eb-8307-a675c43ba07b.png)

Logging in will consolidate it to my account, but I'll end up with multiple lists:

![image](https://user-images.githubusercontent.com/1221575/106080860-fda86a80-616b-11eb-8c23-2a55ec4c1d47.png)

**Comment by chandamotiyani** [comment]
@engram-design my bad, but thank you very much for providing the detailed explanation.
