### ISSUE TITLE
Behavior of mergeLastListOnLogin

### ISSUE THREAD

**Issue by leigeber** [verbb/wishlist#75]
I may be misunderstanding the concept behind mergeLastListOnLogin but we're adding the ability to manage multiple lists for the first time and seeing odd behavior for authenticated users.

1. Log in
2. Create a new list
3. Add an element to the new list or don't
4. Log out
5. Log back in and the list is gone and any products within are added to the first list

- Plugin version: 1.4.4
- Craft version: 3.6.6
- Multi-site: No

**Comment by engram-design** [comment]
Yep, I see why this might be confusing, and I've debated removing this setting altogether.

With this setting enabled, and having multiple lists of the same type, when you login, they're merged into a single list. This is _supposed_ to assist with having multiple lists. Let's say you have an account already with a list, but you're not logged in. You add some items to your list - still logged out - but then realise you should login. Upon login - what's to happen to those items you added as a guest, vs items already in your list as a logged in user?

The thinking with this setting is that it'll merge the two lists, deleting the most recent one which is what you're seeing here.

The way to get around this at the moment is to have separate List Types. For instance, you might have a Favourites and Wishlist list and you wouldn't want these to get merged. This setting will only merge lists of the same type.

Maybe I can introduce an additional check that the lists need to have the same title for the merging to occur?

**Comment by leigeber** [comment]
Hey Josh. Makes sense in regards to logged out users for sure, and for this project that's useful behavior. We're using wishlists as projects, which can be as many as the user needs so we aren't just dealing with up to 2 lists per user, so not sure leveraging list types would help?

The title check possibly could work but then we'd need to enforce uniqueness just in case I suppose. Is it possible to leave lists with a userId alone? Only merge ones with a null value? The docs wording would have made me assume that was the intended behavior.

**Comment by engram-design** [comment]
Yep, I think I modified this slightly to match Commerce's behaviour (which coincidentally have also removed this setting for carts). I have added a title check in https://github.com/verbb/wishlist/commit/90433449e5409a69ecb913e8d7f0336ab5cec1a4 but as you mention, maybe not suitable here.

But yes, the docs wording really is around **guest lists**, but the same scenario above is still likely to occur. What if a user adds to their list as a guest, then logs in?

**Comment by leigeber** [comment]
I think it's somewhat reasonable in that case they'd go to the default list although definitely not ideal in our use-case. Might be too complicated but a setting like "mergeListTitle" could be introduced which we'd set to something like "Guest Wishlist". If a list with that name didn't exist then it could be created it on the fly. That way it wouldn't disrupt a potentially purposeful default list. If they always go to the default we might could reserve that exclusively as a guest cart bucket, adding items to a 2nd list from the start, and only showing the default to the user if there are guest items in it to move. Do guest items go to the default or most recent created?

**Comment by engram-design** [comment]
Items are added to the oldest list (of each type), but as you say, it might be better (more logical) that they're added to the default list. My only issue is that we wouldn't want any cross-list-type movement of items. Complex!

**Comment by engram-design** [comment]
I should also mention that I've modified the docs to clarify, and that guest lists are always consolidated against a user when they login. So a guest might add items to their list(s), decide to register, login and their lists will be added to their account.

Maybe you don't need to merge existing lists if you're just after dealing with guest lists?

**Comment by leigeber** [comment]
Makes sense, maybe even just letting the guest list become its own new list would be best, instead of merging or just disappearing?

But to be clear about what we're seeing it isn't guest lists, its the last list the logged in user created being deleted on re-authentication, so as you'd expect that is a major deal and without a resolution we'll have no choice but to disable the feature, which we'd prefer to keep. Just seems it should leave lists with a userId alone regardless of the behavior beyond that.

For now I'll dig into the title comparison update you added but may have to try to do something custom it sounds? If that's the case there aren't any hooks to control the behavior right?

**Comment by leigeber** [comment]
After a quick look should we hook into the login event in Craft and generally replicate your consolidateListsToUser merge logic but just based on the lastIp for lists without a userId?

**Comment by engram-design** [comment]
Yep, this isn't just for guests (I updated the docs to reflect this incorrect note). My recommendation is if you don't want lists to merge on login, you should set `mergeLastListOnLogin` to false. Guest lists will still be moved to a logged-in user when they login - there's no current way to opt-out of that.

As for the title checks, it'll only merge lists if they have the same title, so I might recommend allowing users to set the title of the list when they create it, and listen in a custom module to the [beforeSaveList](https://verbb.io/craft-plugins/wishlist/docs/developers/events#the-beforeSaveList-event) event to validate any existing lists that it's unique. Then, this should all work out of the box, with no further alterations. Or, if you want something more hands-off, you could use that same event to programatically set a unique title.

Otherwise if you're wanting more control you'd have to set `mergeLastListOnLogin` to false and copy the logic in [consolidateListsToUser](https://github.com/verbb/wishlist/blob/craft-3/src/services/Lists.php#L208) into your own module.

**Comment by engram-design** [comment]
Closing due to [1.4.5](https://github.com/verbb/wishlist/releases/tag/1.4.5) adding support for title-comparison, which I think will assist for the most part.
