### ISSUE TITLE
Add list with non-default listType

### ISSUE THREAD

**Issue by superpikar** [verbb/wishlist#76]
**What are you trying to do?**
We want to implement 2 features for our e-commerce :
- save for later
- wishlist 

to achieve that, we set up 2 `listType`, and the wishlist is the default one. 

Each user can create a new list for each listType, then add the items into those lists. But : 
- it seems not possible to **create a new list with predefined `listTypeHandle`**. see https://verbb.io/craft-plugins/wishlist/docs/template-guides/managing-lists#add-list and https://github.com/verbb/wishlist/blob/craft-3/src/services/Lists.php#L148 

**What's your proposed solution?**
would be great if we can define the `listTypeHandle` or `listType.id` then create a list.

**Comment by engram-design** [comment]
You can do this at the moment, just undocumented:

```
<form method="POST">
    <input type="hidden" name="action" value="wishlist/lists/create">
    {{ csrfInput() }}

    <input type="text" name="typeId" value="2">

    <input type="submit" value="Create New List">
</form>
```
