### ISSUE TITLE
Default Wishlist type not created via project config/composer install

### ISSUE THREAD

**Issue by robzor** [verbb/wishlist#77]
**Description**

Hi there, I installed the Wishlist plugin on a local version of a site I am developing. When this was pushed to the staging server, the default List Type 'Wishlist' was not automatically created causing an error message to display referring to the lack of a default list. 

Development tasks that are run on the server with the deployment:
`composer install`
`/craft project-config/apply`

**Steps to reproduce**
1. Install plugin locally
2. Deploy to a new environment that does not have database information about Wishlist

**Additional info**
- Plugin version: 1.4.4
- Craft version: 3.6.7
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.4.5](https://github.com/verbb/wishlist/releases/tag/1.4.5). You may have to run `./craft project-config/rebuild` locally, or manually save the list type to get it into project config. This will only effect new installs.

**Comment by robzor** [comment]
Thank you!
