### ISSUE TITLE
Dompdf set_z_index argument exception

### ISSUE THREAD

**Issue by leigeber** [verbb/wishlist#78]
Getting the following error when generating a PDF with PHP 8.

```round(): Argument #1 ($num) must be of type int|float, string given```

Seems that per https://github.com/barryvdh/laravel-dompdf/issues/757 newer versions resolve the issue.

Any chance of a bump on Dompdf? Thanks.

**Comment by engram-design** [comment]
I can look into this, but the reason for the `~0.8.3` constraint is at the moment to align with Commerce's own DomPDF constraint: https://github.com/craftcms/commerce/blob/develop/composer.json#L24

I'll have to check the differences between 0.8.x and 0.9.x to see if we can support both without breaking changes.

**Comment by vanburenx** [comment]
Looks like **Commerce 4.1.0** has upgraded to **dompdf 2.0.0**. So far I haven't been able to install Wishlist because of the dependency conflict.

```
- Root composer.json requires craftcms/commerce ^4.1.0 -> satisfiable by craftcms/commerce[4.1.0].
- verbb/wishlist 2.0.0-beta.1 requires dompdf/dompdf ^0.8.3 || ^1.0.0 -> satisfiable by dompdf/dompdf[v0.8.3, v0.8.4, v0.8.5, v0.8.6, v1.0.0, ..., v1.2.2].
- You can only install one version of a package, so only one of these can be installed: dompdf/dompdf[v0.8.3, v0.8.4, v0.8.5, v0.8.6, v1.0.0, ..., v1.2.2, v2.0.0].
- craftcms/commerce 4.1.0 requires dompdf/dompdf ^2.0.0 -> satisfiable by dompdf/dompdf[v2.0.0].
- Root composer.json requires verbb/wishlist ^2.0.0-beta.1 -> satisfiable by verbb/wishlist[2.0.0-beta.1].
```

- https://github.com/craftcms/commerce/blob/cfa4c8a98c5d4afb3c28778cb533c5104f38fd23/composer.json#L26
- https://github.com/craftcms/commerce/commit/d5bc4dd620df8541f213d7f7f9362a2b95e9ad85

Thanks!

**Comment by engram-design** [comment]
Added support in [2.0.0](https://github.com/verbb/wishlist/releases/tag/2.0.0)
