### ISSUE TITLE
Support update multiple items to a list

### ISSUE THREAD

**Issue by superpikar** [verbb/wishlist#81]
**What are you trying to do?**
I tried to update multiple items
```
{% for item in items %}
  <input type="hidden" name="items[{{ loop.index }}][itemId]" value="{{ item.id }}">
  <input type="hidden" name="items[{{ loop.index }}][options][qty]" value="..."/>
{% endfor %}
```
but it returns `"itemId must be provided"`
it seems ItemsController doesn't support update multiple items at the moment https://github.com/verbb/wishlist/blob/craft-3/src/controllers/ItemsController.php#L392 

**What's your proposed solution?**
modify update function `actionUpdate()` to support `items` params

**Additional info**
- craftcms/cms: 3.5.17.1
- verbb/wishlist: 1.4.5

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
