### ISSUE TITLE
Items Not Merged

### ISSUE THREAD

**Issue by kerns** [verbb/wishlist#82]
**Description**
List items created when logged in and logged out are no longer merged, and duplicate or parallel lists are created.

**Steps to reproduce**
1. Sign in and add some items to a list
2. Sign out and add other items to what should be the same list
3. Sign in and see two different lists created where there really should be one merged list

**Additional info**
- Plugin version: Latest
- Craft version: Latest
- Multi-site: No

**Additional context**

I feel like I had this working correctly at some point but that it broke a month or two ago...

```
        'allowDuplicates' => false,
        'manageDisabledLists' => true,
        'mergeLastListOnLogin' => true,
        'purgeInactiveLists' => true,
        'purgeInactiveListsDuration' => 'P6M', // 6 months
        'purgeInactiveGuestListsDuration' => 'P1M', // 1 months
```

**Comment by engram-design** [comment]
Sorry about that, fixed in [1.4.6](https://github.com/verbb/wishlist/releases/tag/1.4.6)
