### ISSUE TITLE
Commerce 3.3 compatibility

### ISSUE THREAD

**Issue by nfourtythree** [verbb/wishlist#83]
**Description**
Just a heads up. The upcoming version 3.3 release of Commerce is changing its DomPDF requirement: https://github.com/craftcms/commerce/blob/3.3/composer.json#L24

Version 3.3 is the compatibility version for Craft version 3.6. This means Commerce needs to support PHP 8. Only versions 1.0 and onwards for DomPDF support PHP 8, therefore, forcing an update to this requirement.

Thanks!

**Comment by engram-design** [comment]
Ah, great! This will also affect https://github.com/verbb/gift-voucher and https://github.com/verbb/events

**Comment by engram-design** [comment]
Should be fixed in [1.4.7](https://github.com/verbb/wishlist/releases/tag/1.4.7)
