### ISSUE TITLE
Add the ability to remove a specific list item (with `options`)

### ISSUE THREAD

**Issue by benface** [verbb/wishlist#84]
**What are you trying to do?**
I am trying to remove a specific list item, that is, a list item defined by an element ID and a specific set of options. There could be other list items with the same element ID in the list, but they should all have different options. Unfortunately, at the moment, it looks like the `wishlist/items/remove` endpoint (`ItemsController`'s `actionRemove` method) doesn't accept an `options` param; it just removes the first list item that matches the passed `elementId`.

**What's your proposed solution?**
The `wishlist/items/remove` endpoint could optionally accept an `options` param. When that param is provided, then the "options signature" would be used for finding the item to remove. I don't believe this would be a breaking change, but if it is because the same list could contain items *with* and *without* options (and passing `[]` as `options` wouldn't be distinguishable from not passing `options` at all), then maybe there could be a new endpoint for the "remove with options" behavior.

**Additional context**
While I don't use it in my project, it looks like the `wishlist/items/toggle` endpoint has the same issue/limitation.

**Comment by engram-design** [comment]
Now I look at this endpoint, I'm not quite sure _why_ I haven't used the Wishlist Item's ID itself, as opposed to trying to delete an item by its `elementId`. That would be far easier, if you pass an existing item's ID to remove?

Basically, 

```
{% for item in list.items.all() %}
    <form method="POST">
        <input type="hidden" name="action" value="wishlist/items/remove">
        {{ csrfInput() }}

        <input type="hidden" name="id" value="{{ item.id }}">

        <input type="submit" value="Remove from List">
    </form>
{% endfor %}
```

Would that suffice?

**Comment by benface** [comment]
@engram-design That would work; in my current project it will require a bit of refactoring (as opposed to my suggestion), but I understand why that's the better way forward. I imagine the `wishlist/items/remove` and `wishlist/items/toggle` endpoints could accept either an `elementId` or an `id`, so there's no breaking change?

**Comment by engram-design** [comment]
Decided to add both! To get this early, change your `verbb/wishlist` requirement in `composer.json` to:

```
"require": {
  "verbb/wishlist": "dev-craft-3 as 1.4.7",
  "...": "..."
}
```

Then run `composer update`.

You should be able to use `itemId`:

```
{% for item in list.items.all() %}
    <form method="POST">
        <input type="hidden" name="action" value="wishlist/items/remove">
        {{ csrfInput() }}

        <input type="hidden" name="itemId" value="{{ item.id }}">

        <input type="submit" value="Remove from List">
    </form>
{% endfor %}
```

Or keep using the `elementId` with `options`:

```
<form method="POST">
    <input type="hidden" name="action" value="wishlist/items/toggle">
    {{ csrfInput() }}

    <input type="text" name="elementId" value="{{ entry.id }}">
    <input type="text" name="options" value="...">

    <input type="submit" value="Toggle in List">
</form>
```

**Comment by benface** [comment]
Awesome! Thank you!

**Comment by engram-design** [comment]
Added in [1.4.8](https://github.com/verbb/wishlist/releases/tag/1.4.8)
