### ISSUE TITLE
Custom fields are not added on toggle with multiple items

### ISSUE THREAD

**Issue by iwe-hi** [verbb/wishlist#85]
**Description**
Custom fields aren't stored in the backend when the action is wishlist/items/toggle. The Item itself is stored, only the custom fields are missing. When the action wishlist/items/add is used, everything works fine.

Here is the form data from the request:

![image](https://user-images.githubusercontent.com/78907655/117153239-12c01580-adbb-11eb-90a4-939b67076a5a.png)

**Additional info**
- Plugin version: 1.4.7
- Craft version: 3.6.13
- Multi-site: No

**Comment by engram-design** [comment]
Yeah, the toggle action endpoint was purely for adding and removing quickly.

Added in [1.4.8](https://github.com/verbb/wishlist/releases/tag/1.4.8)
