### ISSUE TITLE
GraphQL Query fails when getting Wishlists by userId

### ISSUE THREAD

**Issue by a-am** [verbb/wishlist#87]
**Description**
When trying to get a wishlist by `userId` via GraphQL we continue to get this error:

> **Cannot query field "wishlists" on type "Query".**

**Steps to reproduce**
1. Use GraphQL query below ↴
```
query ($userId: [QueryArgument]) {
  wishlists(userId: $userId) {
    id
    title
    items {
      title
      id
    }
  }
}
```

**Additional info**
- Plugin version: 1.4.8
- Craft version: 3.6.13
- Multi-site: No

**Additional context**
When testing I have a wishlist with no items for two different users. 

Trying this query in Craft CMS GraphiQL explorer it works however, other methods like VueJs/Apollo or using Insomnia, I get the same error above.

In addition I tried the GraphQL query without params and still received the same error.
```
{
  wishlists {
    id
    title
    items {
      title
      id
    }
  }
}
```

**Comment by engram-design** [comment]
Was this something on your end (due to closing the issue)?

**Comment by a-am** [comment]
@engram-design This was an issue on our end, the whishlists was not enabled in the Schema.  😬
