### ISSUE TITLE
Modify getInList() to allow checking of a specific list

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/wishlist#88]
**What are you trying to do?**
Test whether or not an item is in a specific list

**What's your proposed solution?**
Currently the method getInList() will return true if the item is in any of the user's lists. It would seem sensible to be able to pass an optional list id to this method to return whether or not an item is in a specific list.

**Comment by engram-design** [comment]
You should be able to do this by fetching the item for a specific list:

```
{% set item = craft.wishlist.item(entry.id, list.id) %}

{# Or for a list type, in case the list doesn't yet exist #}
{% set item = craft.wishlist.item(entry.id, null, 'favourites') %}

{% if item.getInList() %}
```

It shouldn't be returning true if it's in _any_ list, but only the default list.

**Comment by peteeveleigh** [comment]
I’ve got a user with 3 different lists of the same type.

I have an item in the 3rd list, and getInList() is returning true.

When you say the “default list” do you mean the “default list type”?
So in my case I have 3 lists of the default type and thus getInList() will return true no matter which list the item is in.

**Comment by peteeveleigh** [comment]
OK I've tested this again and can confirm that getInList() returns true only if the item is in the default list 

So is there a method I can use to determine if the item is in *any* list? Or do I need to loop through all the lists, and check if my element's ID is in the items.elements of the list?

**Comment by engram-design** [comment]
No function like that at the moment. Would a `craft.wishlist.getInUserLists(entry.id)` work for you?

**Comment by engram-design** [comment]
Added in [1.4.9](https://github.com/verbb/wishlist/releases/tag/1.4.9)
