### ISSUE TITLE
Add product variant element via 'add item' in CP

### ISSUE THREAD

**Issue by tom-c** [verbb/wishlist#90]
**What are you trying to do?**
Currently integrating wishlist into our commerce store to allow people to make lists of products (variants).

Have just realised that the admin CP 'add item' function restricts element selection to plain entries – we really need to be able to select products. This will allow us to support a customer if they share their list with us and call/email for recommendations, we can then add suitable products to their list.

**What's your proposed solution?**
I'm hoping it's just a case of opening up the element types to allow for products and product variants.

**Additional context**
I think there's a possible work around using custom fields, however we'd have to have a dummy entry to select as the element in order to be able to save a new item, which is hard to understand for our staff.

**Comment by tom-c** [comment]
Ok, have dug around and see the problem, there's no native way to select across all element types and building a custom selector would be a bit wild.

Perhaps a config setting to allow choice of element type would suffice?

**Comment by engram-design** [comment]
Yep, this is on my list to address - its a bit of a pain in Craft that there's no "select element" functionality - you always need to restrict it to an element type of some sort. So you can't have a "Pick an entry/category/asset/product/variant" modal - which would be great!

We'll need to introduce a dropdown on that screen to select the element type first, then use the element picker modal to pick some. A config setting - while nice in the short term - just wouldn't be flexible enough if you wanted multiple element types in a list, or across different wishlist list types

**Comment by tom-c** [comment]
Ace, glad it's on your radar 🙏 – something else to possibly consider is the placement of the element selection button. Tried it on the staff who maintain our site and they kept missing it over on the right. I know it's a craft convention, but it seems quite lost over there, esp if you have custom fields for the list element in the main panel.

**Comment by engram-design** [comment]
Hmmm, the only alternative is to maybe add it on the left with the title, so that it's "sticky" across multiple custom field tabs

**Comment by tom-c** [comment]
That could work, not critical, just thought I'd give the feedback as thought it useful.

Only other suggestion is you could enforce selection of element via a dialogue on first load of the page, after clicking the 'new item' on the index. Probably too much faff though as the admin side is likely not heavily used (we just have a fairly specific use case in wanting staff to adjust lists while advising customers).

Do you have any plans to use the new field layout designer functions from Craft 3.5? The UI elements would be useful so we can provide inline instructions for admins.

**Comment by engram-design** [comment]
Appreciate the feedback! I'll play around with that idea, but we'd still probably want a dropdown on the edit page to be able to switch between elements.

No plans, but feel free to create another issue and I'll get on it!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
