### ISSUE TITLE
Craft 3.5 field layout designer

### ISSUE THREAD

**Issue by tom-c** [verbb/wishlist#91]
**What are you trying to do?**
We're using Wishlist in a slightly admin heavy way (so that our staff can discuss / tweak lists with customers via phone calls and emails) and would love to have the new UI abilities that came with the new layout designer in Craft 3.5.

This would allow us to have instructions and template snippets display within the Wishlist area in the CP. 

We really want to be able to provide links to the PDF versions of lists for our staff to be able to email during discussion. Currently have this working using Preparse Field but that means it's a text input they have to copy, so not very slick. Having the new UI elements would allow for some twig code to display links to the PDF and other items.

**What's your proposed solution?**
Not done a lot of research but I think it's just a case of updating to / loading in the new field layout designer?

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
