### ISSUE TITLE
Adding item to wishlist via JSON request results in NULL entry title

### ISSUE THREAD

**Issue by jlawrence-yellostudio** [verbb/wishlist#96]
**Description**

When adding item via JSON request the resulting entry title that has just been added ends up NULL. Interestingly when removing the item from the list the entry title is present!

Same behaviour applies to the toggle endpoint.

**Steps to reproduce**
1. Add item to wishlist via wishlist/items/add action via AJAX/XHR.

**Additional info**
- Plugin version: 1.4.10
- Craft version: 3.7.11
- Multi-site: No

**Additional context**
URL:
```
/actions/wishlist/items/add
```
Payload: 
```
{
    "elementId": 54
}
```
![Screenshot 2021-09-06 at 19 01 28](https://user-images.githubusercontent.com/5747299/132251213-24a25d27-6b0b-4118-a99f-9d17553c8ba9.png)
![Screenshot 2021-09-06 at 19 02 53](https://user-images.githubusercontent.com/5747299/132251217-a7939ca6-b357-42a7-903d-ece13dbb6c94.png)

**Comment by engram-design** [comment]
Fixed in [1.4.11](https://github.com/verbb/wishlist/releases/tag/1.4.11)

**Comment by jlawrence-yellostudio** [comment]
@engram-design Great thanks for the quick fix!
