### ISSUE TITLE
Provide duplicate action for front-end users

### ISSUE THREAD

**Issue by engram-design** [verbb/wishlist#98]
Allows front-end users of a list to duplicate their list and items to a new list. Some things to consider:
- Can only be duplicated into the same list type
- Must be for authenticated users only, to prevent bots from cloning zillions of lists + items
- Anyone can duplicate a list from a List reference (clone other users' lists that have shared with you)
- Fix when "Save as new list" doesn't copy across items in the control panel
- Add duplicate action in the control panel
- Allow changing the User owner of a list in the control panel

**Comment by jckvnr** [comment]
Hi Josh, any update on this mate?

**Comment by jckvnr** [comment]
For a quick solution to this - would it be possible to get the functionality to change the user owner in the control panel...
And ideally for admin users they could assign/change a user owner on the front-end when creating/editing lists.
(e.g. they could log in to their own admin/staff account and create a list for a customer/user).

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/wishlist/releases/tag/3.0.0)
