### ISSUE TITLE
Exception thrown when adding custom field

### ISSUE THREAD

**Issue by russback** [verbb/wishlist#99]
**Description**
When adding an item to a list, and error is thrown when adding custom field data:

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\behaviors\CustomFieldBehavior::myField
```

**Steps to reproduce**
This is just using the standard custom field markup (in this case for a Commerce product variant):
```
<form method="post">
  <input type="hidden" name="action" value="wishlist/items/add">
  <input type="hidden" name="elementId" value="{{ variant.id }}">
  {{ successMessageInput('Added '~ product.title ~' to your wishlist.') }}
  {{ csrfInput() }}
  <input type="text" name="fields[myField]" value="My Value">
  <input type="submit" value="Add to wishlist">
</form>
```

**Additional info**
- Plugin version: 1.4.11
- Craft version: 3.7.24
- Multi-site: Yes

**Comment by engram-design** [comment]
The only way I can reproduce this is if you use a handle for the field that doesn't exist for the list type you're trying to add a list item to. Can you verify the default list type has the field (in this example with handle `myField`)?

**Comment by russback** [comment]
> Can you verify the default list type has the field (in this example with handle myField)?

Well that was dumb. Sorry!
